/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;

import java.awt.Point;
import modeloqytetet.Qytetet;

/**
 *
 * @author Migue
 */
public class VistaTablero extends javax.swing.JPanel {

    /**
     * Creates new form VistaTablero
     */
    public VistaTablero() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Calle1Hoteles = new javax.swing.JLabel();
        Calle2Hoteles = new javax.swing.JLabel();
        Calle4Hoteles = new javax.swing.JLabel();
        Calle6Hoteles = new javax.swing.JLabel();
        Calle7Hoteles = new javax.swing.JLabel();
        Calle9Hoteles = new javax.swing.JLabel();
        Calle11Hoteles = new javax.swing.JLabel();
        Calle12Hoteles = new javax.swing.JLabel();
        Calle14Hoteles = new javax.swing.JLabel();
        Calle16Hoteles = new javax.swing.JLabel();
        Calle17Hoteles = new javax.swing.JLabel();
        Calle19Hoteles = new javax.swing.JLabel();
        Calle1Casas = new javax.swing.JLabel();
        Calle2Casas = new javax.swing.JLabel();
        Calle4Casas = new javax.swing.JLabel();
        Calle6Casas = new javax.swing.JLabel();
        Calle7Casas = new javax.swing.JLabel();
        Calle9Casas = new javax.swing.JLabel();
        Calle11Casas = new javax.swing.JLabel();
        Calle12Casas = new javax.swing.JLabel();
        Calle14Casas = new javax.swing.JLabel();
        Calle16Casas = new javax.swing.JLabel();
        Calle17Casas = new javax.swing.JLabel();
        Calle19Casas = new javax.swing.JLabel();
        J4 = new javax.swing.JLabel();
        J3 = new javax.swing.JLabel();
        J2 = new javax.swing.JLabel();
        J1 = new javax.swing.JLabel();
        Tablero = new javax.swing.JLabel();

        setLayout(null);
        add(Calle1Hoteles);
        Calle1Hoteles.setBounds(0, 0, 800, 800);
        add(Calle2Hoteles);
        Calle2Hoteles.setBounds(0, 0, 800, 800);
        add(Calle4Hoteles);
        Calle4Hoteles.setBounds(0, 0, 800, 800);
        add(Calle6Hoteles);
        Calle6Hoteles.setBounds(0, 0, 800, 800);
        add(Calle7Hoteles);
        Calle7Hoteles.setBounds(0, 0, 800, 800);
        add(Calle9Hoteles);
        Calle9Hoteles.setBounds(0, 0, 800, 800);
        add(Calle11Hoteles);
        Calle11Hoteles.setBounds(0, 0, 800, 800);
        add(Calle12Hoteles);
        Calle12Hoteles.setBounds(0, 0, 800, 800);
        add(Calle14Hoteles);
        Calle14Hoteles.setBounds(0, 0, 800, 800);
        add(Calle16Hoteles);
        Calle16Hoteles.setBounds(0, 0, 800, 800);
        add(Calle17Hoteles);
        Calle17Hoteles.setBounds(0, 0, 800, 800);
        add(Calle19Hoteles);
        Calle19Hoteles.setBounds(0, 0, 800, 800);
        add(Calle1Casas);
        Calle1Casas.setBounds(0, 0, 800, 800);
        add(Calle2Casas);
        Calle2Casas.setBounds(0, 0, 800, 800);
        add(Calle4Casas);
        Calle4Casas.setBounds(0, 0, 800, 800);
        add(Calle6Casas);
        Calle6Casas.setBounds(0, 0, 800, 800);
        add(Calle7Casas);
        Calle7Casas.setBounds(0, 0, 800, 800);
        add(Calle9Casas);
        Calle9Casas.setBounds(0, 0, 800, 800);
        add(Calle11Casas);
        Calle11Casas.setBounds(0, 0, 800, 800);
        add(Calle12Casas);
        Calle12Casas.setBounds(0, 0, 800, 800);
        add(Calle14Casas);
        Calle14Casas.setBounds(0, 0, 800, 800);
        add(Calle16Casas);
        Calle16Casas.setBounds(0, 0, 800, 800);
        add(Calle17Casas);
        Calle17Casas.setBounds(0, 0, 800, 800);
        add(Calle19Casas);
        Calle19Casas.setBounds(0, 0, 800, 800);

        J4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Jugador4/0.png"))); // NOI18N
        J4.setEnabled(false);
        add(J4);
        J4.setBounds(0, 0, 800, 800);

        J3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Jugador3/0.png"))); // NOI18N
        J3.setEnabled(false);
        add(J3);
        J3.setBounds(0, 0, 800, 800);

        J2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Jugador2/0.png"))); // NOI18N
        add(J2);
        J2.setBounds(0, 0, 800, 800);

        J1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Jugador1/0.png"))); // NOI18N
        add(J1);
        J1.setBounds(0, 0, 800, 800);

        Tablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/qytetet.png"))); // NOI18N
        add(Tablero);
        Tablero.setBounds(1, -4, 930, 810);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Calle11Casas;
    private javax.swing.JLabel Calle11Hoteles;
    private javax.swing.JLabel Calle12Casas;
    private javax.swing.JLabel Calle12Hoteles;
    private javax.swing.JLabel Calle14Casas;
    private javax.swing.JLabel Calle14Hoteles;
    private javax.swing.JLabel Calle16Casas;
    private javax.swing.JLabel Calle16Hoteles;
    private javax.swing.JLabel Calle17Casas;
    private javax.swing.JLabel Calle17Hoteles;
    private javax.swing.JLabel Calle19Casas;
    private javax.swing.JLabel Calle19Hoteles;
    private javax.swing.JLabel Calle1Casas;
    private javax.swing.JLabel Calle1Hoteles;
    private javax.swing.JLabel Calle2Casas;
    private javax.swing.JLabel Calle2Hoteles;
    private javax.swing.JLabel Calle4Casas;
    private javax.swing.JLabel Calle4Hoteles;
    private javax.swing.JLabel Calle6Casas;
    private javax.swing.JLabel Calle6Hoteles;
    private javax.swing.JLabel Calle7Casas;
    private javax.swing.JLabel Calle7Hoteles;
    private javax.swing.JLabel Calle9Casas;
    private javax.swing.JLabel Calle9Hoteles;
    private javax.swing.JLabel J1;
    private javax.swing.JLabel J2;
    private javax.swing.JLabel J3;
    private javax.swing.JLabel J4;
    private javax.swing.JLabel Tablero;
    // End of variables declaration//GEN-END:variables
    public void iniciar(int jugadores){
        if (jugadores==3)
            J3.setEnabled(true);
        else if(jugadores == 4){
            J3.setEnabled(true);
            J4.setEnabled(true);
        }
    }
    public void pintarCasa(int num_casilla,int num_casa){
        String variable = "Calle"+num_casilla+"Casas";
        if (num_casa>3) num_casa=3; //Cambiar cuando se tenga imagenes de casas especulador.
        switch(variable){
            case "Calle1Casas":
                Calle1Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Casas/Calle"+num_casilla+"/"+num_casa+".png")));
                break;
            case "Calle2Casas":
                Calle2Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Casas/Calle"+num_casilla+"/"+num_casa+".png")));
                break;
            case "Calle4Casas":
                Calle4Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Casas/Calle"+num_casilla+"/"+num_casa+".png")));
                break;
            case "Calle6Casas":
                Calle6Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Casas/Calle"+num_casilla+"/"+num_casa+".png")));
                break;
            case "Calle7Casas":
                Calle7Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Casas/Calle"+num_casilla+"/"+num_casa+".png")));
                break;
            case "Calle9Casas":
                Calle9Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Casas/Calle"+num_casilla+"/"+num_casa+".png")));
                break;
            case "Calle11Casas":
                Calle11Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Casas/Calle"+num_casilla+"/"+num_casa+".png")));
                break;
            case "Calle12Casas":
                Calle12Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Casas/Calle"+num_casilla+"/"+num_casa+".png")));
                break;
            case "Calle14Casas":
                Calle14Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Casas/Calle"+num_casilla+"/"+num_casa+".png")));
                break;
            case "Calle16Casas":
                Calle16Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Casas/Calle"+num_casilla+"/"+num_casa+".png")));
                break;
            case "Calle17Casas":
                Calle17Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Casas/Calle"+num_casilla+"/"+num_casa+".png")));
                break;
            case "Calle19Casas":
                Calle19Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Casas/Calle"+num_casilla+"/"+num_casa+".png")));
                break;        
        }
        
    }
    public void pintarHotel(int num_casilla,int num_hotel){
        String variable = "Calle"+num_casilla+"Hoteles";
        if (num_hotel > 3) num_hotel = 3;
        switch(variable){        
            case "Calle1Hoteles":
                Calle1Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Hoteles/Calle"+num_casilla+"/"+num_hotel+".png")));
                break;
            case "Calle2Hoteles":
                Calle2Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Hoteles/Calle"+num_casilla+"/"+num_hotel+".png")));
                break;
            case "Calle4Hoteles":
                Calle4Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Hoteles/Calle"+num_casilla+"/"+num_hotel+".png")));
                break;
            case "Calle6Hoteles":
                Calle6Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Hoteles/Calle"+num_casilla+"/"+num_hotel+".png")));
                break;
            case "Calle7Hoteles":
                Calle7Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Hoteles/Calle"+num_casilla+"/"+num_hotel+".png")));
                break;
            case "Calle9Hoteles":
                Calle9Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Hoteles/Calle"+num_casilla+"/"+num_hotel+".png")));
                break;
            case "Calle11Hoteles":
                Calle11Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Hoteles/Calle"+num_casilla+"/"+num_hotel+".png")));
                break;
            case "Calle12Hoteles":
                Calle12Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Hoteles/Calle"+num_casilla+"/"+num_hotel+".png")));
                break;
            case "Calle14Hoteles":
                Calle14Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Hoteles/Calle"+num_casilla+"/"+num_hotel+".png")));
                break;
            case "Calle16Hoteles":
                Calle16Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Hoteles/Calle"+num_casilla+"/"+num_hotel+".png")));
                break;
            case "Calle17Hoteles":
                Calle17Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Hoteles/Calle"+num_casilla+"/"+num_hotel+".png")));
                break;
            case "Calle19Hoteles":
                Calle19Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Casas/Calle"+num_casilla+"/"+num_hotel+".png")));
                break;        
        }
    }
    public void eliminarCasasHoteles(int num_casilla){
        String variable = "Calle"+num_casilla;
        switch(variable){
            case "Calle1":
                Calle1Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                Calle1Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                break;
            case "Calle2":
                Calle2Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                Calle2Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                break;
            case "Calle4":
                Calle4Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                Calle4Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                break;
            case "Calle6":
                Calle6Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                Calle6Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                break;
            case "Calle7":
                Calle7Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                Calle7Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                break;
            case "Calle9":
                Calle9Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                Calle9Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                break;
            case "Calle11":
                Calle11Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                Calle11Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                break;
            case "Calle12":
                Calle12Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                Calle12Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                break;
            case "Calle14":
                Calle14Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                Calle14Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                break;
            case "Calle16":
                Calle16Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                Calle16Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                break;
            case "Calle17":
                Calle17Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                Calle17Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                break;
            case "Calle19":
                Calle19Casas.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                Calle19Hoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                break;  
        }
    }
    public void mover(Qytetet juego){
        int jugador = juego.getJugadores().indexOf(juego.getJugadorActual())+1;
        int casilla = juego.getJugadorActual().getCasillaActual().getNumeroCasilla();

        switch(jugador){
            case 1:
                J1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Jugador1/"+casilla+".png")));
                break;
            case 2:
                J2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Jugador2/"+casilla+".png")));
                break;
            case 3:
                J3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Jugador3/"+casilla+".png")));
                break;
            case 4:
                J4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIQytetet/images/Jugador4/"+casilla+".png")));
                break;
        }
    }
  
}
